import React, { useState, useEffect } from "react";
import { cn } from "@/lib/utils";
import { Button } from "@/components/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/card";
import { Badge } from "@/components/badge";
import { Loader2, FileText, Play, Download, AlertCircle } from "lucide-react";
import { audioService } from "@/lib/audioService";
import { LuaPresetParser } from "@/utils/lua-preset-parser";

interface LuaPreset {
  name: string;
  description?: string;
  bands?: Array<{
    frequency: number;
    gain: number;
    q: number;
  }>;
  params?: {
    width: number;
    decay: number;
    damping: number;
    mix: number;
  };
}

interface LuaPresetManagerProps {
  className?: string;
}

export const LuaPresetManager: React.FC<LuaPresetManagerProps> = ({
  className,
}) => {
  const [equalizerPresets, setEqualizerPresets] = useState<LuaPreset[]>([]);
  const [spatializerPresets, setSpatializerPresets] = useState<LuaPreset[]>([]);
  const [loading, setLoading] = useState(false);
  const [activePreset, setActivePreset] = useState<string | null>(null);

  // Load Lua presets on component mount
  useEffect(() => {
    loadLuaPresets();
  }, []);

  const loadLuaPresets = async () => {
    setLoading(true);
    try {
      // Initialize the parser
      const parser = new LuaPresetParser();
      const isInitialized = await parser.initialize();

      if (!isInitialized) {
        console.error("Failed to initialize Lua engine");
        return;
      }

      // Load both types of presets directly from the parser
      const [eqPresets, spatPresets] = await Promise.all([
        parser.loadEqualizerPresets(),
        parser.loadSpatializerPresets()
      ]);

      setEqualizerPresets(eqPresets as LuaPreset[]);
      setSpatializerPresets(spatPresets as LuaPreset[]);
      
      console.log('Loaded equalizer presets:', eqPresets);
      console.log('Loaded spatializer presets:', spatPresets);
    } catch (error) {
      console.error('Failed to load Lua presets:', error);
    } finally {
      setLoading(false);
    }
  };

  const applyPreset = async (preset: LuaPreset, type: 'equalizer' | 'spatializer') => {
    try {
      // We still use audioService to APPLY the preset to the live audio graph
      const success = await audioService.applyLuaPreset(type, preset);
      if (success) {
        setActivePreset(preset.name);
        console.log(`Applied ${type} preset:`, preset.name);
      }
    } catch (error) {
      console.error(`Failed to apply ${type} preset:`, error);
    }
  };

  const exportPreset = (preset: LuaPreset, type: 'equalizer' | 'spatializer') => {
    // Create a downloadable Lua file
    let luaContent = '';
    
    if (type === 'equalizer') {
      luaContent = `-- ${preset.name} Equalizer Preset\n`;
      luaContent += `-- Generated by Super Dribble\n\n`;
      luaContent += `preset = {\n`;
      luaContent += `  name = "${preset.name}",\n`;
      if (preset.description) {
        luaContent += `  description = "${preset.description}",\n`;
      }
      luaContent += `  bands = {\n`;
      preset.bands?.forEach((band, index) => {
        luaContent += `    { frequency = ${band.frequency}, gain = ${band.gain}, q = ${band.q} }`;
        if (index < (preset.bands?.length || 0) - 1) luaContent += ',';
        luaContent += '\n';
      });
      luaContent += `  }\n}`;
    } else {
      luaContent = `-- ${preset.name} Spatializer Preset\n`;
      luaContent += `-- Generated by Super Dribble\n\n`;
      luaContent += `spatial_preset = {\n`;
      luaContent += `  name = "${preset.name}",\n`;
      if (preset.description) {
        luaContent += `  description = "${preset.description}",\n`;
      }
      luaContent += `  params = {\n`;
      if (preset.params) {
        luaContent += `    width = ${preset.params.width},\n`;
        luaContent += `    decay = ${preset.params.decay},\n`;
        luaContent += `    damping = ${preset.params.damping},\n`;
        luaContent += `    mix = ${preset.params.mix}\n`;
      }
      luaContent += `  }\n}`;
    }

    // Create and download file
    const blob = new Blob([luaContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${preset.name.toLowerCase().replace(/\s+/g, '_')}_${type}.lua`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className={cn("space-y-6", className)}>
      <div className="flex items-center justify-between">
        <h3 className="text-lg font-semibold text-eq-text">Lua Presets</h3>
        <Button
          variant="outline"
          size="sm"
          onClick={loadLuaPresets}
          disabled={loading}
          className="text-eq-text-dim hover:text-eq-accent border-eq-border bg-transparent"
        >
          {loading ? (
            <Loader2 className="h-4 w-4 animate-spin" />
          ) : (
            <FileText className="h-4 w-4" />
          )}
          <span className="ml-2">Reload</span>
        </Button>
      </div>

      {/* Equalizer Presets */}
      <Card className="bg-eq-surface border-eq-border">
        <CardHeader>
          <CardTitle className="text-eq-text text-base">Equalizer Presets</CardTitle>
        </CardHeader>
        <CardContent>
          {loading ? (
             <div className="flex justify-center py-4 text-eq-text-dim">
                <Loader2 className="animate-spin" size={20} />
             </div>
          ) : equalizerPresets.length === 0 ? (
            <p className="text-eq-text-dim text-sm">No equalizer presets found</p>
          ) : (
            <div className="space-y-2">
              {equalizerPresets.map((preset, index) => (
                <div
                  key={index}
                  className={cn(
                    "flex items-center justify-between p-3 rounded-lg border transition-colors",
                    activePreset === preset.name
                      ? "bg-eq-accent/10 border-eq-accent"
                      : "bg-eq-surface-light border-eq-border hover:border-eq-accent/50"
                  )}
                >
                  <div className="flex-1">
                    <div className="flex items-center gap-2">
                      <span className="font-medium text-eq-text">{preset.name}</span>
                      {activePreset === preset.name && (
                        <Badge variant="secondary" className="text-xs bg-eq-accent text-eq-background">
                          Active
                        </Badge>
                      )}
                    </div>
                    {preset.description && (
                      <p className="text-sm text-eq-text-dim mt-1">{preset.description}</p>
                    )}
                    {preset.bands && (
                      <p className="text-xs text-eq-text-dim mt-1">
                        {preset.bands.length} bands
                      </p>
                    )}
                  </div>
                  <div className="flex items-center gap-2">
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => applyPreset(preset, 'equalizer')}
                      className="text-eq-text-dim hover:text-eq-accent border-eq-border hover:bg-eq-surface"
                    >
                      <Play className="h-3 w-3" />
                    </Button>
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => exportPreset(preset, 'equalizer')}
                      className="text-eq-text-dim hover:text-eq-accent border-eq-border hover:bg-eq-surface"
                    >
                      <Download className="h-3 w-3" />
                    </Button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Spatializer Presets */}
      <Card className="bg-eq-surface border-eq-border">
        <CardHeader>
          <CardTitle className="text-eq-text text-base">Spatializer Presets</CardTitle>
        </CardHeader>
        <CardContent>
          {loading ? (
             <div className="flex justify-center py-4 text-eq-text-dim">
                <Loader2 className="animate-spin" size={20} />
             </div>
          ) : spatializerPresets.length === 0 ? (
            <p className="text-eq-text-dim text-sm">No spatializer presets found</p>
          ) : (
            <div className="space-y-2">
              {spatializerPresets.map((preset, index) => (
                <div
                  key={index}
                  className={cn(
                    "flex items-center justify-between p-3 rounded-lg border transition-colors",
                    activePreset === preset.name
                      ? "bg-eq-accent/10 border-eq-accent"
                      : "bg-eq-surface-light border-eq-border hover:border-eq-accent/50"
                  )}
                >
                  <div className="flex-1">
                    <div className="flex items-center gap-2">
                      <span className="font-medium text-eq-text">{preset.name}</span>
                      {activePreset === preset.name && (
                        <Badge variant="secondary" className="text-xs bg-eq-accent text-eq-background">
                          Active
                        </Badge>
                      )}
                    </div>
                    {preset.description && (
                      <p className="text-sm text-eq-text-dim mt-1">{preset.description}</p>
                    )}
                    {preset.params && (
                      <p className="text-xs text-eq-text-dim mt-1">
                        Width: {preset.params.width}, Decay: {preset.params.decay}
                      </p>
                    )}
                  </div>
                  <div className="flex items-center gap-2">
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => applyPreset(preset, 'spatializer')}
                      className="text-eq-text-dim hover:text-eq-accent border-eq-border hover:bg-eq-surface"
                    >
                      <Play className="h-3 w-3" />
                    </Button>
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => exportPreset(preset, 'spatializer')}
                      className="text-eq-text-dim hover:text-eq-accent border-eq-border hover:bg-eq-surface"
                    >
                      <Download className="h-3 w-3" />
                    </Button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
};